### ISSUE TITLE
Install CLI without the GUI?

### ISSUE THREAD

**Issue by jhiggins** [sveinbjornt/Platypus#270]
Is there a way to install the CLI without using the user interface? The shell script in the bundle, as noted elsewhere, is templated.

**Comment by chris1111** [comment]
unzip platypus_clt.gz
Use `platypus_clt -h`

**Comment by michaelherger** [comment]
I'd be very interested, too. As I hope to be able to run builds in a Github action, we would need a way to run the CLI version completely without GUI.

**Comment by michaelherger** [comment]
Thanks @berleant! Your hint in https://github.com/sveinbjornt/Platypus/issues/245#issuecomment-1995407445 was spot on (except that some of the files are gzipped and need to be extracted. Here's my Github Action snippet which would build a Hello World application using the Platypus CLI. Assuming the three files mentioned in the above comment and the sample script are in your repo's `Bin/darwin/platypus` folder:

```yaml
      - name: Platypus Test
        run: |
          cd Bin/darwin/platypus

          sudo mkdir -p /usr/local/share/platypus || echo $?
          sudo cp -nfr * /usr/local/share/platypus || echo $?

          /usr/local/share/platypus/platypus_clt -y helloworld.sh
          zip -r9 HelloWorld.zip Helloworld.app

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: Bin/darwin/platypus/HelloWorld.zip
```
